### ISSUE TITLE
exception during sync and playback

### ISSUE THREAD

**Issue by eratosthene** [eratosthene/kmpc#65]
Looks like this happens if the track changes while on the system tab:

> [ERROR  ] [update_mpd_currentsong] list index out of range
> Traceback (most recent call last):
>   File "/home/sysop/kmpc/kmpc/kmpcapp.py", line 329, in update_mpd_currentsong
    img_path=os.path.join(al_path,random.choice(os.listdir(al_path)))
>   File "/usr/lib/python2.7/random.py", line 275, in choice
    return seq[int(self.random() * len(seq))]  # raises IndexError if seq is empty
> IndexError: list index out of range

**Comment by eratosthene** [comment]
Can't reproduce.
